#!/usr/bin/env python3
"""
gen_schema.py — แปลง base44/entities/*.jsonc  →  PostgreSQL DDL + RLS baseline
รันซ้ำได้ (idempotent output). ใช้เป็นจุดเริ่มของ migration/schema.sql
"""
import json, re, sys, os
from pathlib import Path

ENT_DIR = Path(sys.argv[1] if len(sys.argv) > 1 else "base44/entities")
OUT = Path(sys.argv[2] if len(sys.argv) > 2 else "schema.sql")

RESERVED = {"user", "order", "group", "default", "check", "table", "column", "references",
            "select", "from", "where", "grant", "role", "end", "session", "authorization"}

def strip_jsonc(s):
    s = re.sub(r'/\*.*?\*/', '', s, flags=re.S)
    s = re.sub(r'^\s*//.*$', '', s, flags=re.M)
    return s

def snake(name):
    s = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', name)
    s = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1_\2', s)
    return re.sub(r'_+', '_', s).lower().strip('_')

def table_name(entity):
    # TaxQA_Filing -> taxqa_filing ; Task -> tasks (pluralise เฉพาะคำเดียวสั้น ๆ ไม่ทำ เพื่อลดความกำกวม)
    t = snake(entity)
    return f'"{t}"' if t in RESERVED else t

def pg_type(prop):
    t = prop.get("type")
    fmt = prop.get("format")
    if t == "string":
        if fmt == "date":       return "date"
        if fmt == "date-time":  return "timestamptz"
        return "text"
    if t == "number":  return "numeric"
    if t == "integer": return "integer"
    if t == "boolean": return "boolean"
    if t in ("array", "object"): return "jsonb"
    return "text"          # fallback: untyped / oneOf

def sql_default(prop, pgt):
    if "default" not in prop: return None
    d = prop["default"]
    if pgt == "jsonb":
        return f"'{json.dumps(d, ensure_ascii=False)}'::jsonb"
    if isinstance(d, bool):  return "true" if d else "false"
    if isinstance(d, (int, float)): return str(d)
    if d == "": return "''"
    return "'" + str(d).replace("'", "''") + "'"

def col_ident(name):
    return f'"{name}"' if (name in RESERVED or not re.fullmatch(r'[a-z_][a-z0-9_]*', name)) else name

entities = {}
for f in sorted(ENT_DIR.glob("*.jsonc")):
    entities[f.stem] = json.loads(strip_jsonc(f.read_text(encoding="utf-8")))

out = []
w = out.append

w("-- ============================================================================")
w("-- ACC Operation System — PostgreSQL schema (generated from Base44 entities)")
w("-- generated by gen_schema.py — ตรวจสอบและปรับ business constraint ก่อนใช้ production")
w("-- ============================================================================")
w("")
w("create extension if not exists pgcrypto;")
w("")
w("-- ---------------------------------------------------------------------------")
w("-- helper: updated_date auto-touch (แทน behaviour ของ Base44)")
w("-- ---------------------------------------------------------------------------")
w("create or replace function public.touch_updated_date() returns trigger")
w("language plpgsql as $$ begin new.updated_date := now(); return new; end $$;")
w("")

# ---------- profiles (จาก entity User) ----------
user_ent = entities.pop("User", None)
w("-- ===========================================================================")
w("-- profiles — แทน built-in User entity ของ Base44 (ผูก 1:1 กับ auth.users)")
w("-- ===========================================================================")
w("create table if not exists public.profiles (")
w("  id          uuid primary key references auth.users(id) on delete cascade,")
w("  email       text not null unique,")
w("  full_name   text,")
w("  created_date timestamptz not null default now(),")
w("  updated_date timestamptz not null default now(),")
if user_ent:
    props = user_ent.get("properties", {})
    req = set(user_ent.get("required", []))
    for name, p in props.items():
        pgt = pg_type(p)
        line = f"  {col_ident(name):<24} {pgt}"
        d = sql_default(p, pgt)
        if d: line += f" default {d}"
        if name in req: line += " not null"
        line += ","
        if p.get("description"):
            line += "  -- " + p["description"].replace("\n", " ")[:90]
        w(line)
w("  _placeholder boolean default null")
w(");")
w("")
if user_ent:
    for name, p in user_ent.get("properties", {}).items():
        if "enum" in p:
            vals = ", ".join("'" + str(v).replace("'", "''") + "'" for v in p["enum"])
            w(f"alter table public.profiles drop constraint if exists profiles_{name}_chk;")
            w(f"alter table public.profiles add constraint profiles_{name}_chk")
            w(f"  check ({col_ident(name)} is null or {col_ident(name)} in ({vals}));")
    w("")
w("-- helper: อ่าน role ของผู้ใช้ปัจจุบันจาก profiles")
w("create or replace function public.current_app_role() returns text")
w("language sql stable security definer set search_path = '' as $$")
w("  select role from public.profiles where id = auth.uid()")
w("$$;")
w("")
w("-- helper: email ของผู้ใช้ปัจจุบัน (โค้ดเดิมเทียบ created_by กับ email)")
w("create or replace function public.current_email() returns text")
w("language sql stable security definer set search_path = '' as $$")
w("  select email from public.profiles where id = auth.uid()")
w("$$;")
w("")
w("drop trigger if exists trg_profiles_touch on public.profiles;")
w("create trigger trg_profiles_touch before update on public.profiles")
w("  for each row execute function public.touch_updated_date();")
w("")
w("-- สร้าง profile อัตโนมัติเมื่อมี auth user ใหม่")
w("create or replace function public.handle_new_user() returns trigger")
w("language plpgsql security definer set search_path = '' as $$")
w("begin")
w("  insert into public.profiles (id, email, full_name)")
w("  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'full_name', new.email))")
w("  on conflict (id) do nothing;")
w("  return new;")
w("end $$;")
w("")
w("drop trigger if exists on_auth_user_created on auth.users;")
w("create trigger on_auth_user_created after insert on auth.users")
w("  for each row execute function public.handle_new_user();")
w("")

# ---------- entity tables ----------
STD = """  id            text primary key default ('e' || replace(gen_random_uuid()::text, '-', '')),
  created_date  timestamptz not null default now(),
  updated_date  timestamptz not null default now(),
  created_by    text default public.current_email(),   -- Base44 เก็บเป็น email
  created_by_id uuid default auth.uid(),"""

tables = []
for ent, spec in entities.items():
    tbl = table_name(ent)
    tables.append((ent, tbl))
    props = spec.get("properties", {})
    req = set(spec.get("required", []))
    w("-- ===========================================================================")
    w(f"-- {ent}  ({len(props)} fields)")
    w("-- ===========================================================================")
    w(f"create table if not exists public.{tbl} (")
    w(STD)
    for name, p in props.items():
        pgt = pg_type(p)
        line = f"  {col_ident(name):<28} {pgt}"
        d = sql_default(p, pgt)
        if d: line += f" default {d}"
        if name in req: line += " not null"
        line += ","
        if p.get("description"):
            line += "  -- " + p["description"].replace("\n", " ")[:80]
        w(line)
    w("  _placeholder boolean default null")
    w(");")
    w("")
    for name, p in props.items():
        if "enum" in p and p.get("type") == "string":
            vals = ", ".join("'" + str(v).replace("'", "''") + "'" for v in p["enum"])
            cn = f"{snake(ent)}_{name}_chk"[:60]
            w(f"alter table public.{tbl} drop constraint if exists {cn};")
            w(f"alter table public.{tbl} add constraint {cn}")
            w(f"  check ({col_ident(name)} is null or {col_ident(name)} in ({vals}));")
    w(f"drop trigger if exists trg_{snake(ent)[:50]}_touch on public.{tbl};")
    w(f"create trigger trg_{snake(ent)[:50]}_touch before update on public.{tbl}")
    w("  for each row execute function public.touch_updated_date();")
    # index บน field ที่ลงท้าย _id / _email / status / *_date
    for name, p in props.items():
        if re.search(r'(_id|_email)$', name) or name in ("status", "key", "customer_id"):
            w(f"create index if not exists idx_{snake(ent)[:40]}_{name[:20]} on public.{tbl} ({col_ident(name)});")
    w("")

# ---------- RLS ----------
w("-- ===========================================================================")
w("-- RLS BASELINE")
w("-- Base44 ไม่มี row-level rule ในไฟล์ entity เลย → พฤติกรรมเดิมคือ")
w("-- 'ผู้ใช้ที่ล็อกอินแล้วเข้าถึงได้ทั้งหมด' (คุมสิทธิ์ที่ชั้น UI ด้วย menu_permissions)")
w("-- baseline นี้จึงรักษาพฤติกรรมเดิมไว้ = authenticated เข้าถึงได้ / anon เข้าไม่ได้")
w("-- >>> ตารางที่มีข้อมูลอ่อนไหวถูกยกเป็น policy เข้มกว่าด้านล่าง <<<")
w("-- ===========================================================================")
w("")
SENSITIVE = {"CustomerCredential", "DirectorInfo", "AuditLog"}
w("alter table public.profiles enable row level security;")
w("drop policy if exists profiles_select on public.profiles;")
w("create policy profiles_select on public.profiles for select to authenticated using (true);")
w("drop policy if exists profiles_update_self on public.profiles;")
w("create policy profiles_update_self on public.profiles for update to authenticated")
w("  using (id = auth.uid() or public.current_app_role() in ('admin','management'));")
w("drop policy if exists profiles_admin_all on public.profiles;")
w("create policy profiles_admin_all on public.profiles for all to authenticated")
w("  using (public.current_app_role() = 'admin') with check (public.current_app_role() = 'admin');")
w("")
for ent, tbl in tables:
    w(f"alter table public.{tbl} enable row level security;")
    base = snake(ent)[:45]
    if ent in SENSITIVE:
        w(f"-- {ent}: ข้อมูลอ่อนไหว (PDPA) — จำกัด role")
        w(f"drop policy if exists {base}_ro on public.{tbl};")
        w(f"create policy {base}_ro on public.{tbl} for select to authenticated")
        w(f"  using (public.current_app_role() in ('admin','management','manager'));")
        w(f"drop policy if exists {base}_rw on public.{tbl};")
        w(f"create policy {base}_rw on public.{tbl} for all to authenticated")
        w(f"  using (public.current_app_role() in ('admin','management'))")
        w(f"  with check (public.current_app_role() in ('admin','management'));")
    else:
        w(f"drop policy if exists {base}_all on public.{tbl};")
        w(f"create policy {base}_all on public.{tbl} for all to authenticated")
        w(f"  using (true) with check (true);")
    w("")

w("-- ===========================================================================")
w("-- GO-LIVE GATE: ต้องคืนผลลัพธ์ว่าง ห้าม deploy ถ้าไม่ว่าง")
w("-- ===========================================================================")
w("-- select tablename from pg_tables where schemaname='public' and rowsecurity=false;")
w("-- select c.relname from pg_class c join pg_namespace n on n.oid=c.relnamespace")
w("--   where n.nspname='public' and c.relkind='r' and c.relrowsecurity")
w("--   and not exists (select 1 from pg_policy p where p.polrelid=c.oid);")

OUT.write_text("\n".join(out) + "\n", encoding="utf-8")

# --- emit explicit entity -> table map (ใช้ใน shim ทั้ง client และ server) ---
mapping = {"User": "profiles"}
for ent, tbl in tables:
    mapping[ent] = tbl.strip('"')
js = ["// AUTO-GENERATED by gen_schema.py — entity name (Base44) -> Postgres table",
      "export const ENTITY_TABLE = " + json.dumps(mapping, indent=2, ensure_ascii=False, sort_keys=True) + ";",
      "",
      "export function tableFor(entity) {",
      "  const t = ENTITY_TABLE[entity];",
      "  if (!t) throw new Error(`Unknown entity: ${entity}`);",
      "  return t;",
      "}"]
Path(str(OUT).replace('.sql', '') + '_entity_map.js').write_text("\n".join(js) + "\n", encoding="utf-8")
print("wrote entity map:", len(mapping), "entities")
print(f"wrote {OUT}  ({len(out)} lines)")
print(f"entities: {len(tables)+1} tables (incl. profiles)")
