#!/usr/bin/env node
/**
 * gen-keys.mjs — สร้าง secret ทั้งหมดที่ Supabase self-hosted ต้องใช้
 *   node infra/gen-keys.mjs >> infra/.env
 * แล้วเปิด .env เติมค่าที่เหลือ (SMTP, ANTHROPIC_API_KEY, GOOGLE_*)
 *
 * สร้าง: POSTGRES_PASSWORD, JWT_SECRET, ANON_KEY, SERVICE_ROLE_KEY,
 *        DASHBOARD_PASSWORD, SECRET_KEY_BASE, VAULT_ENC_KEY, RESTIC_PASSWORD
 * ANON_KEY / SERVICE_ROLE_KEY เป็น JWT (HS256) เซ็นด้วย JWT_SECRET จริง
 */
import { randomBytes, createHmac } from 'node:crypto';

const b64url = (buf) =>
  Buffer.from(buf).toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');

function jwt(payload, secret) {
  const header = { alg: 'HS256', typ: 'JWT' };
  const enc = (o) => b64url(JSON.stringify(o));
  const data = `${enc(header)}.${enc(payload)}`;
  const sig = b64url(createHmac('sha256', secret).update(data).digest());
  return `${data}.${sig}`;
}

const rand = (n) => randomBytes(n).toString('base64').replace(/[^a-zA-Z0-9]/g, '').slice(0, n);

const JWT_SECRET = rand(48);
const iat = Math.floor(Date.now() / 1000);
const exp = iat + 60 * 60 * 24 * 365 * 10; // 10 ปี

const ANON_KEY = jwt({ role: 'anon', iss: 'supabase', iat, exp }, JWT_SECRET);
const SERVICE_ROLE_KEY = jwt({ role: 'service_role', iss: 'supabase', iat, exp }, JWT_SECRET);

const out = {
  POSTGRES_PASSWORD: rand(32),
  JWT_SECRET,
  ANON_KEY,
  SERVICE_ROLE_KEY,
  DASHBOARD_USERNAME: 'acc-admin',
  DASHBOARD_PASSWORD: rand(24),
  SECRET_KEY_BASE: rand(64),
  VAULT_ENC_KEY: rand(32),
  RESTIC_PASSWORD: rand(32),
};

console.log('# ===== generated by gen-keys.mjs — เก็บเป็นความลับ =====');
for (const [k, v] of Object.entries(out)) console.log(`${k}=${v}`);
console.error('สร้าง secret เรียบร้อย — อย่าลืมเติม SMTP_*, ANTHROPIC_API_KEY, GOOGLE_* ใน .env ด้วย');
